### ISSUE TITLE
Gophish Webhook Signature Verification Fails

### ISSUE THREAD

**Issue by er4z0r** [t94j0/gophish-notifier#3]
I tried to integrate gophish-notifier with my 0.12.1 gophish.

Configuration

```
# Host to listen on. If GoPhish is running on the same host, you can set this to 127.0.0.1
listen_host: 127.0.0.1
# Port to listen on
listen_port: 9999
# Webhook path. The full address will be http://<host>:<ip><webhook_path>. Ex: http://127.0.0.1:9999/webhook
webhook_path: /webhook
# Secret for GoPhish authentication
secret: secretpassword123
# Log level. Log levels are panic, fatal, error, warning, info, debug, trace.
log_level: debug
# (Optional) Base URL of GoPhish instance so that Slack notifications can link to campaign
base_url: https://127.0.0.1:3333
# Enables sending profiles. Options are `slack` and `email`. Make sure to configure the required parameters for each profile
profiles:
  - slack

# Slack Profile
slack:
  # Webhook address. Typically starts with https://hooks.slack.com/services/...
  webhook: 'https://hooks.slack.com/services/XXXXXXXXXXXXXXXXXXXXXXXX'
  # Username displayed in Slack
  username: Gophish
  # Channel to post in
  bot_channel: '#phish'
  # Bot profile picture
  emoji: ':blowfish:'
  # (Optional) Disable email, username, and credentials from being sent to Slack
  disable_credentials: true

# Email Profile
# Email to send from
email:
  sender: test@test.com
  # Password of sender email. Uses plain SMTP authentication
  sender_password: password123
  # Recipient of notifications
  recipient: mail@example.com
  # Email host to send to
  host: smtp.gmail.com
  # Email host address
  host_addr: smtp.gmail.com:587

# You can also supply an email template for each notification
email_submitted_credentials_template: |
  Someone submitted credentials!
  Email ID - {{ .ID }}
  Email Address - {{ .Email }}
  IP Address - {{ .Address }}
  User Agent - {{ .UserAgent }}
  Username - {{ .Username }}
  Password - {{ .Password }}
```
I got the following doing "Ping" in gophish. Same issue also occurs with actual cred submissions.
```
~/gophish-notifier$ ./gophish-notifier
INFO[0000] Using config file: /home/er4z0r/gophish-notifier/config.yml
INFO[0000] Using Slack sending profile. Will send messages to #phish
INFO[0000] Server listening on 127.0.0.1:9999/webhook
DEBU[0019] {"success":true}
ERRO[0019] invalid signature 
```
Below is a tcpdump -A
```
11:17:26.500793 IP localhost.42824 > localhost.9999: Flags [P.], seq 1:258, ack 1, win 512, options [nop,nop,TS val 2565852676 ecr 2565852675], length 257
E..5?k@.@..U.........H'.../.Z........).....
........POST /webhook HTTP/1.1
Host: 127.0.0.1:9999
User-Agent: Go-http-client/1.1
Content-Length: 16
Content-Type: application/json
X-Signature: sha256=a3d9e29720841a77d50b27f64c0fdae99d0fdbd9ea2f944c6e0a75b8bab53170
Accept-Encoding: gzip

{"success":true}
11:17:26.500816 IP localhost.9999 > localhost.42824: Flags [.], ack 258, win 510, options [nop,nop,TS val 2565852676 ecr 2565852676], length 0
E..4K3@.@...........'..HZ.....0......(.....
........
11:17:26.501019 IP localhost.9999 > localhost.42824: Flags [P.], seq 1:178, ack 258, win 512, options [nop,nop,TS val 2565852676 ecr 2565852676], length 177
E...K4@.@...........'..HZ.....0............
........HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 09 Apr 2024 11:17:26 GMT
Content-Length: 18

invalid signature
```
